### PR TITLE
Atom Support

### PR DESCRIPTION
**Pull request by wstrinz**
Addresses https://github.com/bendyworks/buffet/issues/43
- [x] install common Atom plugins if `apm` is available
- [ ] configure keybindings (?)
- [ ] configure plugins (?)
- [ ] themes (?)

### CODE REVIEW

**Comment by abraham** [comment]
These are the packages I have that are mostly on topic for BW usage.

```
Sublime-Style-Column-Selection
atom-beautify
atom-bootstrap3
atom-jshint
atom-material-syntax
atom-material-ui
atom-pair
autocomplete-ruby
file-icons
highlight-selected
language-ampscript
language-crontab
language-gherkin
language-haml
linter
linter-erb
linter-htmlhint
linter-js-yaml
linter-jscs
linter-rubocop
linter-ruby
merge-conflicts
pigments
pretty-json
rails-rspec
rspec
```

**Comment by kliph** [comment]
Would prefer some keybinding(s) for toggling support for vim keybindings and emacs keybindings.  Don't know what these packages are called,  but the ability to toggle them is lit!  See c1ba7807 for potential keys (e.g. ⌘-/ toggles vim keybindings).

**Comment by vizjerai** [comment]
Packages that I have enabled

```
Sublime-Style-Column-Selection
atom-typescript
autocomplete-ruby
highlight-selected
language-rspec
linter
linter-js-yaml
linter-rubocop
markdown-scroll-sync
merge-conflicts
rails-rspec
rails-transporter
ruby-test
toggle-quotes
vim-mode-plus
```

**Comment by wstrinz** [comment]
@vizjerai @abraham ; added!

@kliph still investigating how to reconfigure atom keybindings; I don't suppose you know of an emacs package or any other atom specific interface?

**Comment by wstrinz** [comment]
@kliph https://atom.io/packages/atomic-emacs or https://atom.io/packages/emacs-plus ?

**Comment by kliph** [comment]
@wstrinz `atomic-emacs` seems good to me.

**Comment by vizjerai** [comment]
https://atom.io/packages/toggle-packages

**Comment by wstrinz** [comment]
:thanks:, updated

**Comment by wstrinz** [comment]
merging this in since it's been out a while. other sorts of configuration can go in another PR

**Pull request merged**
