### PR TITLE
Proposal: Delete .rubocop.yml

### PR DESCRIPTION
**Pull request by listrophy**
Given different clients might have different rubocop requirements, I propose we delete this file. Otherwise, a rubocop-pass on one of our computers might be a rubocop-fail on a client's computer (or CI).

### CODE REVIEW

**Comment by abraham** [comment]
Maybe there is a way of telling rubocop to ignore the global if there as a repo local one? I want to have a system default.

**Comment by listrophy** [comment]
A cursory investigation of the [configuration](https://rubocop.readthedocs.io/en/latest/configuration/) page indicates that there doesn't seem to be a way to ignore `~/.rubocop.yml`.

**Comment by abraham** [comment]
Just a note that the bendyworks.com linting currently depends on this repo's file.

**Comment by abraham** [comment]
I think this is also not an issue if using `bundle exec`.

**Pull request merged**
