### PR TITLE
Add dot emacs

### PR DESCRIPTION
**Pull request by kliph**
Tested on mal.  YMMV 🚗

### CODE REVIEW

**Comment by kliph** [comment]
@wstrinz This PR begins to address #44 💯

**Comment by kliph** [comment]
Plz hold off on merging for now.  I'm going to address issues #47 and #48 on this branch too.

**Comment by kliph** [comment]
@wstrinz ready for review and merging

**Comment by wstrinz** [comment]
yep definitely some ELisp right in thar 😛 

looks good to me, we can handle any issues people have if they come up

**Pull request merged**
